# Generated by Django 4.1.7 on 2023-03-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cover',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='resume',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
    ]
