# Generated by Django 4.1.7 on 2023-03-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_created_job_created_on_job_applied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
