# Generated by Django 4.1.7 on 2023-03-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_job_cover_job_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cover',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='resume',
            field=models.CharField(default='', max_length=500),
        ),
    ]
