# Generated by Django 4.1.7 on 2023-04-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_job_cover_alter_job_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_position',
            field=models.CharField(default='A', max_length=250),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_address',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_email',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
